/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteRouteImport } from './routes/media/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as MediaIdRouteImport } from './routes/media/$id'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaDownloadIdRouteImport } from './routes/api/media/download.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRouteRoute = MediaRouteRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIdRoute = MediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MediaRouteRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaDownloadIdRoute = ApiMediaDownloadIdRouteImport.update({
  id: '/api/media/download/$id',
  path: '/api/media/download/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/media': typeof MediaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/upload': typeof AdminUploadRoute
  '/media/$id': typeof MediaIdRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/download/$id': typeof ApiMediaDownloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/upload': typeof AdminUploadRoute
  '/media/$id': typeof MediaIdRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/media': typeof MediaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/download/$id': typeof ApiMediaDownloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/media': typeof MediaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/upload': typeof AdminUploadRoute
  '/media/$id': typeof MediaIdRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/media/': typeof MediaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/download/$id': typeof ApiMediaDownloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/media'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/upload'
    | '/media/$id'
    | '/uploads/$'
    | '/admin/'
    | '/media/'
    | '/api/auth/$'
    | '/api/media/download/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/upload'
    | '/media/$id'
    | '/uploads/$'
    | '/admin'
    | '/media'
    | '/api/auth/$'
    | '/api/media/download/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/media'
    | '/login'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/upload'
    | '/media/$id'
    | '/uploads/$'
    | '/admin/'
    | '/media/'
    | '/api/auth/$'
    | '/api/media/download/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MediaRouteRoute: typeof MediaRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaDownloadIdRoute: typeof ApiMediaDownloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/download/$id': {
      id: '/api/media/download/$id'
      path: '/api/media/download/$id'
      fullPath: '/api/media/download/$id'
      preLoaderRoute: typeof ApiMediaDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MediaRouteRouteChildren {
  MediaIdRoute: typeof MediaIdRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

const MediaRouteRouteChildren: MediaRouteRouteChildren = {
  MediaIdRoute: MediaIdRoute,
  MediaIndexRoute: MediaIndexRoute,
}

const MediaRouteRouteWithChildren = MediaRouteRoute._addFileChildren(
  MediaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MediaRouteRoute: MediaRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaDownloadIdRoute: ApiMediaDownloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
